[package]
name = "xiao-bytecode"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "Xiao bytecode format and instruction model"

[lib]
path = "src/lib.rs"

[dependencies]
xiao-ir = { path = "../xiao-ir" }
xiao-lifetime = { path = "../xiao-lifetime" }
xiao-syntax = { path = "../xiao-syntax" }

[dev-dependencies]
xiao-driver = { path = "../xiao-driver" }
