[package]
name = "xiao-syntax"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "Xiao lexer, parser and syntax tree"

[lib]
path = "src/lib.rs"

[dependencies]
xiao-diagnostics = { path = "../xiao-diagnostics" }
xiao-source = { path = "../xiao-source" }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
